- name: Call AAP Server to Provision
  hosts: localhost
  connection: local
  tasks:
    - name: Call AAP Server
      awx.awx.job_launch:
        controller_host: "{{ lookup('ansible.builtin.ini', 'hostname', section='provision',  file='/etc/ansible/provision.ini') }}"
        controller_username: "{{ lookup('ansible.builtin.ini', 'username', section='provision',  file='/etc/ansible/provision.ini') }}"
        controller_password: "{{ lookup('ansible.builtin.ini', 'password', section='provision',  file='/etc/ansible/provision.ini') }}"
        job_template: "{{ lookup('ansible.builtin.ini', 'job_template', section='provision',  file='/etc/ansible/provision.ini') }}"
        validate_certs: false
        extra_vars:
          server_type: "{{ lookup('ansible.builtin.ini', 'server_type', section='provision',  file='/etc/ansible/provision.ini') }}"
          ipaddress: "{{ ansible_default_ipv4.address }}"
          macaddress: "{{ ansible_default_ipv4.macaddress }}"
